#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle wrapper.
# NOTE: This is the standard Gradle wrapper shell script. If gradle/wrapper/gradle-wrapper.jar
# is missing (e.g. it could not be downloaded in a restricted network environment), run:
#   gradle wrapper --gradle-version 8.7
# using a locally installed Gradle to regenerate it before using this script.
#

APP_HOME=$(cd "$(dirname "$0")" && pwd)
APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and 'java' command could not be found."
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    die "ERROR: $CLASSPATH not found. Run 'gradle wrapper --gradle-version 8.7' with a local Gradle install to generate it, or use the CI workflow which installs Gradle directly."
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
